<a href="https://colab.research.google.com/github/bharaniakella/deep_learning/blob/main/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# matrix1=m*n
# matrix2=n*k
#matmul result -> m*k

In [1]:
import numpy as np
import torch

In [3]:
#matrix multiplication with numpy

n1=np.random.randn(4,5)
n2=np.random.randn(5,4)
print(n1)
print("\n")
print(n2)

[[-0.32630816  0.52554526 -0.5479598  -0.44207293 -0.59130907]
 [ 0.28133924  1.68101246 -0.20902315  0.67908897  0.7518349 ]
 [-0.92703562  0.08927851  0.07858804 -0.4876     -0.43877525]
 [ 0.71013407 -1.08750645 -1.28551383  0.71273038 -0.1211067 ]]


[[ 0.39132314  1.68580497 -0.20172656 -0.81121753]
 [ 0.26602302  0.82101933  1.11101939 -1.33392104]
 [ 0.06827554  0.06852612  0.09998363 -0.10530917]
 [-0.25419056 -0.68999876 -0.16300611  1.28172055]
 [-0.92645711 -2.88956221 -0.21932247  0.09150474]]


In [4]:
#using np.matmul

np.matmul(n1,n2)

array([[ 0.6348962 ,  1.85749544,  0.79667694, -0.99934533],
       [-0.3261494 , -0.80094099,  1.514395  , -1.50935442],
       [ 0.19679506,  0.12019523,  0.46977044, -0.04045593],
       [-0.16814819,  0.07435472, -1.56964198,  1.91239027]])

In [5]:
# using @ -> same as matmul

n1@n2

array([[ 0.6348962 ,  1.85749544,  0.79667694, -0.99934533],
       [-0.3261494 , -0.80094099,  1.514395  , -1.50935442],
       [ 0.19679506,  0.12019523,  0.46977044, -0.04045593],
       [-0.16814819,  0.07435472, -1.56964198,  1.91239027]])

In [9]:
#matmul with transpose

a=np.random.randn(3,5)
b=np.random.randn(3,4)

print(a)
print("\n")
print(b)
print("\n")
a.T@b

[[-0.2215637   0.23596027  1.4587311  -0.10811849 -1.02967608]
 [-1.26392804  1.82181596 -1.59040018  0.09558279  0.39735238]
 [ 0.174832    1.17732913 -1.42239158 -0.64064483 -0.14405647]]


[[-5.95653184e-01  8.40441777e-02  2.01327205e-01 -2.88376866e-01]
 [-7.15309027e-01 -1.41124598e-03 -1.49570641e+00  1.29397670e+00]
 [-7.97008775e-01  8.65387208e-01 -5.23003869e-01  5.40864881e-01]]




array([[ 0.89673163,  0.13445995,  1.75442066, -1.4770391 ],
       [-2.38205353,  1.03610562, -3.29314428,  2.9261179 ],
       [ 1.40238835, -1.10607717,  3.4163703 , -3.24792673],
       [ 0.50662944, -0.56362746,  0.17032873, -0.19164151],
       [ 0.44391436, -0.21176367, -0.72628221,  0.73318439]])

In [10]:
np.matmul(a.T,b)

array([[ 0.89673163,  0.13445995,  1.75442066, -1.4770391 ],
       [-2.38205353,  1.03610562, -3.29314428,  2.9261179 ],
       [ 1.40238835, -1.10607717,  3.4163703 , -3.24792673],
       [ 0.50662944, -0.56362746,  0.17032873, -0.19164151],
       [ 0.44391436, -0.21176367, -0.72628221,  0.73318439]])

In [11]:
#matrix multiplication with pytorch

t1=torch.randn(3,2)
t2=torch.randn(3,4)
print(t1)
print("\n")
print(t2)

tensor([[ 1.3219,  2.2816],
        [-0.8467, -0.4761],
        [ 0.3909,  0.4752]])


tensor([[-1.0028, -0.1004,  1.2148, -0.1541],
        [ 0.7267,  1.0810, -0.5107,  0.9949],
        [-0.9395,  0.1110,  0.6253,  1.2839]])


In [12]:
print(t1.T@t2)

tensor([[-2.3080, -1.0045,  2.2827, -0.5442],
        [-3.0804, -0.6909,  3.3121, -0.2151]])


In [13]:
print(t2.T@t1)

tensor([[-2.3080, -3.0804],
        [-1.0045, -0.6909],
        [ 2.2827,  3.3121],
        [-0.5442, -0.2151]])
