<a href="https://colab.research.google.com/github/bharaniakella/deep_learning/blob/main/min_max_argmin_argmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a=[2,-1,40,3]
print(np.min(a))
print(np.max(a))
print(np.argmax(a))
print(np.argmin(a))

-1
40
2
1


In [5]:
b=np.array([[4,5,1],[8,3,11]])
print(b)
print(np.min(b))
print(np.min(b,axis=0))
print(np.min(b,axis=1))

[[ 4  5  1]
 [ 8  3 11]]
1
[4 3 1]
[1 3]


In [6]:
b=np.array([[4,5,1],[8,3,11]])
print(b)
print(np.argmin(b))
print(np.argmin(b,axis=0))
print(np.argmin(b,axis=1))

[[ 4  5  1]
 [ 8  3 11]]
2
[0 1 0]
[2 1]


In [9]:
#using torch
import torch
z=torch.Tensor([[4,5,1],[8,3,11]])
print(z)
print(torch.argmin(z))
print(torch.argmin(z,axis=0))
print(torch.argmin(z,axis=1))

tensor([[ 4.,  5.,  1.],
        [ 8.,  3., 11.]])
tensor(2)
tensor([0, 1, 0])
tensor([2, 1])
