<a href="https://colab.research.google.com/github/bharaniakella/deep_learning/blob/main/transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries
import numpy as np
import torch

In [ ]:
n1=np.array([[1,2,3,4]])
print(n1)

[[1 2 3 4]]


In [ ]:
#transposing array
n1T=n1.T
print(n1T)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
#transposing matrix
n2=np.array([[1,2,3],[4,5,6]])
print(n2)
n2T=n2.T
print("\n")
print(n2T)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#transpose -> 1d tensor
ten1=torch.Tensor([[1,2,3]])
print(ten1)
ten1T=ten1.T
print(ten1T)

tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])


In [ ]:
ten2=torch.tensor([[1,2,3],[4,5,6]])
print(ten2)
print("\n")
ten2T=ten2.T
print(ten2T)

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])
